export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILS = "REGISTRATION_FAILS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILS = "LOGIN_FAILS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILS = "AUTH_FAILS";

export const FETCH_FEEDS_START = "FETCH_FEEDS_START";
export const FETCH_FEEDS = "FETCH_FEEDS";
export const FETCH_FEEDS_FAILS = "FETCH_FEEDS_FAILS";

export const FETCH_TWEETS_START = "FETCH_TWEETS_START";
export const FETCH_TWEETS = "FETCH_TWEETS";
export const FETCH_TWEETS_FAILS = "FETCH_TWEETS_FAILS";

export const TOGGLE_IS = "TOGGLE_IS";
export const ADD_TWEET = "ADD_TWEET";

export const USER_START = "USER_START";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILS = "USER_FAILS";

export const ADD_FOLLOWER = "ADD_FOLLOWER";
export const LOGOUT = "LOGOUT";
