// ADD PRODUCT
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_RPODUCT_FAILURE'

// GET PRODUCT
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_RPODUCT_FAILURE'

// FILTER PRODUCT
export const FILTER_PRODUCT_REQUEST = 'FILTER_PRODUCT_REQUEST'
export const FILTER_PRODUCT_SUCCESS = 'FILTER_PRODUCT_SUCCESS'
export const FILTER_PRODUCT_FAILURE = 'FILTER_PRODUCT_FAILURE'

// SORT PRODUCT
export const SORT_PRODUCT_REQUEST = 'SORT_PRODUCT_REQUEST'
export const SORT_PRODUCT_SUCCESS = 'SORT_PRODUCT_SUCCESS'
export const SORT_PRODUCT_FAILURE = 'SORT_PRODUCT_FAILURE'