import {LOGIN} from './Action'

const initialState = {
    data : [{
        "Floor_No": 1,
        "Meeting_Room_Name": "Haleigh",
        "Capacity": 7,
        "Price": 3351
      }, {
        "Floor_No": 2,
        "Meeting_Room_Name": "Donella",
        "Capacity": 22,
        "Price": 3344
      }, {
        "Floor_No": 3,
        "Meeting_Room_Name": "Romy",
        "Capacity": 21,
        "Price": 3095
      }, {
        "Floor_No": 4,
        "Meeting_Room_Name": "Laurie",
        "Capacity": 33,
        "Price": 3777
      }, {
        "Floor_No": 5,
        "Meeting_Room_Name": "Roland",
        "Capacity": 45,
        "Price": 2142
      }, {
        "Floor_No": 6,
        "Meeting_Room_Name": "Corbie",
        "Capacity": 14,
        "Price": 4879
      }, {
        "Floor_No": 7,
        "Meeting_Room_Name": "Emilee",
        "Capacity": 30,
        "Price": 3597
      }, {
        "Floor_No": 8,
        "Meeting_Room_Name": "Leah",
        "Capacity": 12,
        "Price": 4547
      }, {
        "Floor_No": 9,
        "Meeting_Room_Name": "Broderick",
        "Capacity": 16,
        "Price": 3537
      }, {
        "Floor_No": 10,
        "Meeting_Room_Name": "Mikael",
        "Capacity": 29,
        "Price": 2054
      }, {
        "Floor_No": 11,
        "Meeting_Room_Name": "Kelsey",
        "Capacity": 30,
        "Price": 1675
      }, {
        "Floor_No": 12,
        "Meeting_Room_Name": "Osbert",
        "Capacity": 36,
        "Price": 4487
      }, {
        "Floor_No": 13,
        "Meeting_Room_Name": "Linzy",
        "Capacity": 45,
        "Price": 4087
      }, {
        "Floor_No": 14,
        "Meeting_Room_Name": "Scot",
        "Capacity": 47,
        "Price": 3114
      }, {
        "Floor_No": 15,
        "Meeting_Room_Name": "Gustie",
        "Capacity": 15,
        "Price": 4649
      }, {
        "Floor_No": 16,
        "Meeting_Room_Name": "Cortney",
        "Capacity": 33,
        "Price": 4700
      }, {
        "Floor_No": 17,
        "Meeting_Room_Name": "Guinevere",
        "Capacity": 48,
        "Price": 1946
      }, {
        "Floor_No": 18,
        "Meeting_Room_Name": "Percy",
        "Capacity": 13,
        "Price": 3185
      }, {
        "Floor_No": 19,
        "Meeting_Room_Name": "Pen",
        "Capacity": 41,
        "Price": 2768
      }, {
        "Floor_No": 20,
        "Meeting_Room_Name": "Andrej",
        "Capacity": 5,
        "Price": 4120
      }, {
        "Floor_No": 21,
        "Meeting_Room_Name": "Querida",
        "Capacity": 49,
        "Price": 4956
      }, {
        "Floor_No": 22,
        "Meeting_Room_Name": "Josselyn",
        "Capacity": 44,
        "Price": 3714
      }, {
        "Floor_No": 23,
        "Meeting_Room_Name": "Hazel",
        "Capacity": 45,
        "Price": 4137
      }, {
        "Floor_No": 24,
        "Meeting_Room_Name": "Brandyn",
        "Capacity": 30,
        "Price": 1765
      }, {
        "Floor_No": 25,
        "Meeting_Room_Name": "Lola",
        "Capacity": 30,
        "Price": 1925
      }, {
        "Floor_No": 26,
        "Meeting_Room_Name": "Claudia",
        "Capacity": 37,
        "Price": 3709
      }, {
        "Floor_No": 27,
        "Meeting_Room_Name": "Arlyne",
        "Capacity": 12,
        "Price": 3403
      }, {
        "Floor_No": 28,
        "Meeting_Room_Name": "Layton",
        "Capacity": 29,
        "Price": 1650
      }, {
        "Floor_No": 29,
        "Meeting_Room_Name": "Adrianna",
        "Capacity": 16,
        "Price": 2809
      }, {
        "Floor_No": 30,
        "Meeting_Room_Name": "Sonya",
        "Capacity": 22,
        "Price": 4152
      }, {
        "Floor_No": 31,
        "Meeting_Room_Name": "Lillian",
        "Capacity": 20,
        "Price": 3120
      }, {
        "Floor_No": 32,
        "Meeting_Room_Name": "Annamarie",
        "Capacity": 37,
        "Price": 2262
      }, {
        "Floor_No": 33,
        "Meeting_Room_Name": "Vail",
        "Capacity": 20,
        "Price": 4207
      }, {
        "Floor_No": 34,
        "Meeting_Room_Name": "Normy",
        "Capacity": 17,
        "Price": 2803
      }, {
        "Floor_No": 35,
        "Meeting_Room_Name": "Rey",
        "Capacity": 13,
        "Price": 2221
      }, {
        "Floor_No": 36,
        "Meeting_Room_Name": "Lorens",
        "Capacity": 23,
        "Price": 3268
      }, {
        "Floor_No": 37,
        "Meeting_Room_Name": "Nevins",
        "Capacity": 35,
        "Price": 2016
      }, {
        "Floor_No": 38,
        "Meeting_Room_Name": "Evita",
        "Capacity": 24,
        "Price": 3831
      }, {
        "Floor_No": 39,
        "Meeting_Room_Name": "Natal",
        "Capacity": 13,
        "Price": 2494
      }, {
        "Floor_No": 40,
        "Meeting_Room_Name": "Georas",
        "Capacity": 23,
        "Price": 3075
      }, {
        "Floor_No": 41,
        "Meeting_Room_Name": "Karilynn",
        "Capacity": 10,
        "Price": 4547
      }, {
        "Floor_No": 42,
        "Meeting_Room_Name": "Elnore",
        "Capacity": 5,
        "Price": 2736
      }, {
        "Floor_No": 43,
        "Meeting_Room_Name": "Oneida",
        "Capacity": 5,
        "Price": 1811
      }, {
        "Floor_No": 44,
        "Meeting_Room_Name": "Jerry",
        "Capacity": 43,
        "Price": 4749
      }, {
        "Floor_No": 45,
        "Meeting_Room_Name": "Sibella",
        "Capacity": 33,
        "Price": 2366
      }, {
        "Floor_No": 46,
        "Meeting_Room_Name": "Rita",
        "Capacity": 38,
        "Price": 1723
      }, {
        "Floor_No": 47,
        "Meeting_Room_Name": "Alayne",
        "Capacity": 50,
        "Price": 4020
      }, {
        "Floor_No": 48,
        "Meeting_Room_Name": "Flin",
        "Capacity": 7,
        "Price": 3664
      }, {
        "Floor_No": 49,
        "Meeting_Room_Name": "Zedekiah",
        "Capacity": 33,
        "Price": 3215
      }, {
        "Floor_No": 50,
        "Meeting_Room_Name": "Sunny",
        "Capacity": 25,
        "Price": 4908
      }],
    form : false,
    token : ""
}

const Reducer = (state = initialState, action) =>{
    switch(action.type)
    {
        case LOGIN :
            console.log(action.payload)
            if(action.payload.status == 200){
                return {
                    form : true,
                    token : action.payload.token,
                    data : state.data
                }
            }     
        default:
            return state
    }
}

export default Reducer