export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
export const REGISTER_SECCESFULL = "REGISTER_SUCCESSFULL";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";
