// fetch all category
export const FETCH_ALL_CATEGORY_REQUEST = "FETCH_ALL_CATEGORY_REQUEST";
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS";
export const FETCH_ALL_CATEGORY_FAILURE = "FETCH_ALL_CATEGORY_FAILURE";

// fetch all author
export const FETCH_ALL_AUTHOR_REQUEST = "FETCH_ALL_AUTHOR_REQUEST";
export const FETCH_ALL_AUTHOR_SUCCESS = "FETCH_ALL_AUTHOR_SUCCESS";
export const FETCH_ALL_AUTHOR_FAILURE = "FETCH_ALL_AUTHOR_FAILURE";

// fetch all publisher
export const FETCH_ALL_PUBLISHER_REQUEST = "FETCH_ALL_PUBLISHER_REQUEST";
export const FETCH_ALL_PUBLISHER_SUCCESS = "FETCH_ALL_PUBLISHER_SUCCESS";
export const FETCH_ALL_PUBLISHER_FAILURE = "FETCH_ALL_PUBLISHER_FAILURE";

// fetch all books
export const FETCH_ALL_BOOK_REQUEST = "FETCH_ALL_BOOK_REQUEST";
export const FETCH_ALL_BOOK_SUCCESS = "FETCH_ALL_BOOK_SUCCESS";
export const FETCH_ALL_BOOK_FAILURE = "FETCH_ALL_BOOK_FAILURE";
